/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ApplyContact: typeof import('./src/components/ApplyContact.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    CoverTest: typeof import('./src/components/CoverTest.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    NoData: typeof import('./src/components/NoData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Titlebar: typeof import('./src/components/Titlebar.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  }
}
